# Generated by Django 6.0.6 on 2026-07-08 06:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('destination', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('hotel_name', models.CharField(max_length=100)),
                ('places_visited', models.TextField(help_text='Enter places separated by commas.')),
                ('hotel_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('travel_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('food_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('other_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='trip_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
